//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int id { get; set; }
        public string KitapAdi { get; set; }
        public string Yazar { get; set; }
        public string Tur { get; set; }
        public int SayfaSayisi { get; set; }
        public int BasimYili { get; set; }
        public string YayinEvi { get; set; }
        public int Adet { get; set; }
    }
}
